## Фреймворк PyTorch для разработки искусственных нейронных сетей

### Домашнее задание №1

In [2]:
import torch

**1. Создайте случайный FloatTensor размера 3x4x5**

In [3]:
X = torch.rand(3,4,5)
print(X)
print(X.type())

tensor([[[0.8361, 0.2487, 0.2342, 0.0537, 0.5055],
         [0.0315, 0.9232, 0.7547, 0.9320, 0.6082],
         [0.4045, 0.3434, 0.7030, 0.1553, 0.7739],
         [0.9118, 0.9329, 0.6341, 0.2137, 0.6676]],

        [[0.6964, 0.8377, 0.0188, 0.2922, 0.3973],
         [0.6448, 0.0267, 0.2033, 0.4496, 0.2711],
         [0.6056, 0.1173, 0.6349, 0.3401, 0.3101],
         [0.7127, 0.9649, 0.6416, 0.2217, 0.4968]],

        [[0.0801, 0.8348, 0.4347, 0.8849, 0.2907],
         [0.7968, 0.8505, 0.7056, 0.2442, 0.5280],
         [0.2842, 0.0564, 0.3358, 0.6609, 0.4963],
         [0.0202, 0.7164, 0.3472, 0.2301, 0.3367]]])
torch.FloatTensor


**2. Выведите его форму (shape)**

In [4]:
print(X.shape,)

torch.Size([3, 4, 5])


**3. Приведите его к форме 6х10**

In [6]:
X = X.reshape(6, 10)
print(X)

tensor([[0.8361, 0.2487, 0.2342, 0.0537, 0.5055, 0.0315, 0.9232, 0.7547, 0.9320,
         0.6082],
        [0.4045, 0.3434, 0.7030, 0.1553, 0.7739, 0.9118, 0.9329, 0.6341, 0.2137,
         0.6676],
        [0.6964, 0.8377, 0.0188, 0.2922, 0.3973, 0.6448, 0.0267, 0.2033, 0.4496,
         0.2711],
        [0.6056, 0.1173, 0.6349, 0.3401, 0.3101, 0.7127, 0.9649, 0.6416, 0.2217,
         0.4968],
        [0.0801, 0.8348, 0.4347, 0.8849, 0.2907, 0.7968, 0.8505, 0.7056, 0.2442,
         0.5280],
        [0.2842, 0.0564, 0.3358, 0.6609, 0.4963, 0.0202, 0.7164, 0.3472, 0.2301,
         0.3367]])


**4. Создайте случайный IntTensor размера 10**

In [7]:
Y = torch.randint(low=1,high=10,size=[1,10])
print(Y)
print(Y.type())

tensor([[3, 5, 6, 5, 9, 1, 3, 6, 4, 5]])
torch.LongTensor


**5. Умножьте созданный FloatTensor на созданный IntTensor поэлементно**

In [8]:
mult_elem = X * Y
print(mult_elem)

tensor([[2.5083, 1.2436, 1.4054, 0.2684, 4.5499, 0.0315, 2.7695, 4.5280, 3.7281,
         3.0408],
        [1.2135, 1.7172, 4.2179, 0.7765, 6.9649, 0.9118, 2.7986, 3.8046, 0.8547,
         3.3382],
        [2.0892, 4.1885, 0.1130, 1.4608, 3.5754, 0.6448, 0.0802, 1.2198, 1.7984,
         1.3556],
        [1.8167, 0.5866, 3.8093, 1.7006, 2.7909, 0.7127, 2.8947, 3.8498, 0.8866,
         2.4839],
        [0.2402, 4.1738, 2.6079, 4.4246, 2.6165, 0.7968, 2.5516, 4.2337, 0.9769,
         2.6399],
        [0.8526, 0.2820, 2.0150, 3.3043, 4.4667, 0.0202, 2.1493, 2.0831, 0.9202,
         1.6835]])


**6. Умножьте тензор матрично на себя, чтобы результат был размерности 6x6**  
*Подсказка: .dot может не подойти*

In [9]:
mult_matrix = torch.mm(X,torch.transpose(X, 1, 0))
print(mult_matrix)

tensor([[3.7355, 2.9615, 1.7939, 2.7654, 2.4624, 1.9599],
        [2.9615, 3.9939, 1.9543, 3.3603, 3.3592, 2.0380],
        [1.7939, 1.9543, 2.1636, 1.6046, 2.0701, 0.9392],
        [2.7654, 3.3603, 1.6046, 3.1420, 2.9713, 1.9173],
        [2.4624, 3.3592, 2.0701, 2.9713, 3.9544, 2.0493],
        [1.9599, 2.0380, 0.9392, 1.9173, 2.0493, 1.6803]])


**7. Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)**

In [10]:
x=torch.tensor(1.0, requires_grad=True) 
z=torch.tensor(0.5, requires_grad=True) 
t=torch.tensor(2.0, requires_grad=True) 
y=x**3+z-75*t 
y.backward() 

Производная:

In [12]:
x.grad, z.grad, t.grad 

(tensor(3.), tensor(1.), tensor(-75.))

**8. Создайте единичный тензор размера 5x6**

In [13]:
ones = torch.ones([5,6])
print(ones)
print(ones.type())

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])
torch.FloatTensor


**9. Переведите его в формат numpy**

In [15]:
ones = ones.numpy()
print(ones)
print(type(ones))

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
<class 'numpy.ndarray'>
