### Домашнее задание №1

In [1]:
import torch

In [2]:
# 1. Создайте случайный FloatTensor размера 3x4x5

In [3]:
X = torch.rand(3,4,5)

In [4]:
print(X)
print(X.type())

tensor([[[0.7969, 0.2347, 0.3844, 0.0568, 0.4446],
         [0.1678, 0.6032, 0.9535, 0.6511, 0.5380],
         [0.2436, 0.7896, 0.2283, 0.5631, 0.4720],
         [0.2518, 0.9949, 0.2689, 0.2494, 0.2125]],

        [[0.4864, 0.0557, 0.7199, 0.9189, 0.6148],
         [0.8201, 0.8696, 0.2360, 0.3070, 0.4726],
         [0.3628, 0.4472, 0.0101, 0.2144, 0.1042],
         [0.3940, 0.3935, 0.7907, 0.6644, 0.6256]],

        [[0.0861, 0.1552, 0.8336, 0.8521, 0.8031],
         [0.4509, 0.8911, 0.4051, 0.8989, 0.6974],
         [0.8505, 0.6705, 0.4775, 0.1557, 0.6211],
         [0.7651, 0.5684, 0.0171, 0.8807, 0.5570]]])
torch.FloatTensor


In [5]:
# 2. Выведите его форму (shape)

In [6]:
print(X.shape,)

torch.Size([3, 4, 5])


In [7]:
# 3. Приведите его к форме 6х10

In [8]:
X = X.reshape(6, 10)
print(X)

tensor([[0.7969, 0.2347, 0.3844, 0.0568, 0.4446, 0.1678, 0.6032, 0.9535, 0.6511,
         0.5380],
        [0.2436, 0.7896, 0.2283, 0.5631, 0.4720, 0.2518, 0.9949, 0.2689, 0.2494,
         0.2125],
        [0.4864, 0.0557, 0.7199, 0.9189, 0.6148, 0.8201, 0.8696, 0.2360, 0.3070,
         0.4726],
        [0.3628, 0.4472, 0.0101, 0.2144, 0.1042, 0.3940, 0.3935, 0.7907, 0.6644,
         0.6256],
        [0.0861, 0.1552, 0.8336, 0.8521, 0.8031, 0.4509, 0.8911, 0.4051, 0.8989,
         0.6974],
        [0.8505, 0.6705, 0.4775, 0.1557, 0.6211, 0.7651, 0.5684, 0.0171, 0.8807,
         0.5570]])


In [9]:
# 4. Создайте случайный IntTensor размера 10

In [10]:
Y = torch.randint(low=1,high=10,size=[1,10])
print(Y)
print(Y.type())

tensor([[7, 9, 7, 3, 6, 2, 1, 8, 4, 9]])
torch.LongTensor


In [11]:
# 5. Умножьте созданный FloatTensor на созданный IntTensor поэлементно

In [12]:
mult_elem = X * Y
print(mult_elem)

tensor([[5.5785, 2.1121, 2.6908, 0.1703, 2.6676, 0.3355, 0.6032, 7.6282, 2.6045,
         4.8424],
        [1.7052, 7.1067, 1.5978, 1.6892, 2.8322, 0.5037, 0.9949, 2.1514, 0.9977,
         1.9129],
        [3.4045, 0.5014, 5.0391, 2.7568, 3.6889, 1.6402, 0.8696, 1.8880, 1.2282,
         4.2535],
        [2.5395, 4.0244, 0.0706, 0.6432, 0.6250, 0.7880, 0.3935, 6.3259, 2.6576,
         5.6301],
        [0.6025, 1.3968, 5.8353, 2.5564, 4.8188, 0.9017, 0.8911, 3.2407, 3.5956,
         6.2766],
        [5.9533, 6.0342, 3.3423, 0.4670, 3.7263, 1.5303, 0.5684, 0.1368, 3.5226,
         5.0126]])


In [13]:
# 6. Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
# Подсказка: .dot может не подойти

In [14]:
mult_matrix = torch.mm(X,torch.transpose(X, 1, 0))
print(mult_matrix)

tensor([[3.0534, 1.8845, 2.3442, 2.2830, 2.7908, 2.6642],
        [1.8845, 2.5077, 2.4465, 1.6157, 2.6741, 2.3271],
        [2.3442, 2.4465, 3.7823, 1.8212, 3.7732, 2.9790],
        [2.2830, 1.6157, 1.8212, 2.1566, 2.2575, 2.1834],
        [2.7908, 2.6741, 3.7732, 2.2575, 4.5533, 3.2451],
        [2.6642, 2.3271, 2.9790, 2.1834, 3.2451, 3.8052]])


In [15]:
# 7. Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

In [16]:
x=torch.tensor(1.0, requires_grad=True) 
z=torch.tensor(0.5, requires_grad=True) 
t=torch.tensor(2.0, requires_grad=True) 
y=x**3+z-75*t 
y.backward() 

In [17]:
x.grad 

tensor(3.)

In [18]:
z.grad

tensor(1.)

In [19]:
t.grad 

tensor(-75.)

In [20]:
# 8. Создайте единичный тензор размера 5x6

In [21]:
ones = torch.ones([5,6])
print(ones)
print(ones.type())

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])
torch.FloatTensor


In [22]:
# 9. Переведите его в формат numpy

In [23]:
ones = ones.numpy()
print(ones)
print(type(ones))

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
<class 'numpy.ndarray'>
